import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { LangProvider } from "@/components/LangProvider";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Casefy — Practice PM interviews with AI",
  description:
    "Casefy is an AI-powered Product Manager interview simulator. Run live cases on real products and get scored across 7 PM dimensions. Get hired.",
  openGraph: {
    title: "Casefy — Practice PM interviews with AI. Get hired.",
    description:
      "Live PM case interviews generated by AI, scored across 7 dimensions.",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.variable}>
      <body className="bg-canvas text-white antialiased font-sans min-h-screen">
        <LangProvider>{children}</LangProvider>
      </body>
    </html>
  );
}
